# Generated by Django 5.0.1 on 2024-01-03 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_account_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_notifications',
        ),
    ]
