# Generated by Django 5.0.1 on 2024-01-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='desc',
            field=models.TextField(default='Полное описание сайта', verbose_name='Описание ссылки'),
        ),
    ]
